#! /bin/sh

docker image rm seekworser/swabian-time-tagger
docker build --no-cache=true --rm -t seekworser/swabian-time-tagger .
docker-machine rm -y swabian-time-tagger
docker-machine create -d virtualbox --virtualbox-disk-size 2000 swabian-time-tagger
docker-machine stop swabian-time-tagger
vboxmanage modifyvm swabian-time-tagger --natpf1 "swabian-time-tagger,tcp,,8888,,8888" --usb on --usbehci on
vboxmanage usbfilter add 0 --target swabian-time-tagger --name "time-tagger" --vendorid 151f --productid 0023
